# Numpy

## 2D array

In [2]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [3]:
print (a_list)
print (a_list[1])
print (a_list[1][1])

print ([ row[0] for row in a_list] )

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[5, 6, 7, 8]
6
[1, 5, 9]


In [4]:
import numpy as np

In [5]:
np_array = np.array( a_list )
print(np_array)
print(type(np_array) )
print(np_array[1])
print(np_array[1][1])
print(np_array[1, 1], '\n') # [row index, column index]

print( np_array[ :, 0 ] )
print( np_array[ :, 2 ], '\n' )

print( np_array[ :2, 0 ], '\n' )

print( np_array[ :2, 1:3 ], '\n' )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
[5 6 7 8]
6
6 

[1 5 9]
[ 3  7 11] 

[1 5] 

[[2 3]
 [6 7]] 



In [10]:
print ( np_array.shape )
print (len(np_array) )

(3, 4)
3


In [12]:
print (np_array[ :2, 1:3 ].shape )

(2, 2)


# 1D array

In [6]:
array_1d = np.array( [1,5,7,9,71,14] )

print ( array_1d.shape )
print (len (array_1d) )
print ( array_1d)

(6,)
6
[ 1  5  7  9 71 14]


In [15]:
list_1d = [1,5,7,9,71,14]
print ( list_1d * 3 )
print ( [ number * 3 for number in list_1d ] )
print ('numpy array')
print ( array_1d * 3 )
print ( array_1d / 3 )
print ( array_1d + 3 )
print ( array_1d % 2 )
print ( array_1d ** 5 )

[1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14]
[3, 15, 21, 27, 213, 42]
numpy array
[  3  15  21  27 213  42]
[ 0.33333333  1.66666667  2.33333333  3.         23.66666667  4.66666667]
[ 4  8 10 12 74 17]
[1 1 1 1 1 0]
[         1       3125      16807      59049 1804229351     537824]


In [17]:
print (array_1d)
list_1d = [1,5,7,9,71,14]
print (list_1d)
list_1d[2:4] = [10,25]
print (list_1d)
# list_1d[2:4] = 50 # error
# print (list_1d)
print ('numpy array')
array_1d[2:4] = [10,25]
print (array_1d)
array_1d[2:4] = 55
print (array_1d)

[ 1  5  7  9 71 14]
[1, 5, 7, 9, 71, 14]
[1, 5, 10, 25, 71, 14]
numpy array
[ 1  5 10 25 71 14]
[ 1  5 55 55 71 14]


# 3D array

In [20]:
arr_3d = np.array([
        [ 
            [1, 2, 3], 
            [4, 5, 6]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)
print (arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [19]:
print ( arr_3d.shape )

(2, 2, 3)


In [21]:
arr_3d[:, :, 2] = 10
print(arr_3d)
arr_3d[:, :, 2] = 55
print(arr_3d)

[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [ 4  5 10]]]
[[[ 1  2 55]
  [ 4  5 55]]

 [[ 1  2 55]
  [ 4  5 55]]]


In [23]:
arr_3d[:, :, 2] = 10
print(arr_3d)
arr_3d[1, 1, :2] = 55
print(arr_3d)

[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [ 4  5 10]]]
[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [55 55 10]]]


# Numpy speed

In [9]:
size = 1_000_000

In [10]:
%%timeit # Jupyter komanda

py_list = list(range(size))

85.5 ms ± 6.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
%%timeit

np_arr = np.arange(size)

38.4 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
%%timeit

py_list_2 = [ number * 2 for number in py_list ]

NameError: name 'py_list' is not defined

In [29]:
%%timeit

np_rez = np_arr * 2

NameError: name 'np_arr' is not defined

# Numpy reshape

In [13]:
np_array = np.arange(0,100,2)
print(np_array)
print(np_array.shape)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [14]:
print( np_array.reshape( (5,10) ), '\n' )

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]] 



In [15]:
print( np_array.reshape( (2,25) ) )

[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
  48]
 [50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
  98]]


In [16]:
print( np_array.reshape( (5, 2, 5) ) )

[[[ 0  2  4  6  8]
  [10 12 14 16 18]]

 [[20 22 24 26 28]
  [30 32 34 36 38]]

 [[40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]]

 [[80 82 84 86 88]
  [90 92 94 96 98]]]


In [17]:
print( np_array.reshape( (5, 5, 5) ) )

ValueError: cannot reshape array of size 50 into shape (5,5,5)

In [19]:
print( np_array.reshape( (2, 1, -1) ) ) # -1 palieka tiek kiek telpa

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


# Numpy methods

In [38]:
array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [2,2], [4,3], [7,4] ],
    [ [3,2], [4,3], [7,4] ],
    [ [4,2], [4,3], [7,4] ],
]
)

print (array_3d.shape)

TypeError: 'numpy.ndarray' object is not callable

In [31]:
print (array_3d)

[[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]


In [30]:
np.mean (array_3d)

3.75

In [42]:
print ( 'matrix mean\n', np.mean (array_3d, axis=0 ) )

matrix mean
 [[2.5 2. ]
 [4.  3. ]
 [7.  4. ]]


In [43]:
print ( 'Column mean\n', print (np.mean (array_3d, axis=1 ) ) )
# print (np.mean (array_3d, axis=1 ).shape)

[[4.         3.        ]
 [4.33333333 3.        ]
 [4.66666667 3.        ]
 [5.         3.        ]]
Column mean
 None


In [41]:
print ( 'Row mean', np.mean (array_3d, axis=2 ) ) # row

Row mean [[1.5 3.5 5.5]
 [2.  3.5 5.5]
 [2.5 3.5 5.5]
 [3.  3.5 5.5]]


In [28]:
np.array = np.arange(0,20).reshape( (5,4) )
print (np_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [45]:
print('Column mean',  np.mean( np_array, axis=0 ) ) 
print('Row mean', np.mean( np_array, axis=1 ) ) 

Column mean 49.0


AxisError: axis 1 is out of bounds for array of dimension 1

In [50]:
print (np_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [52]:
np.std( np_array)

28.861739379323623

In [55]:
print('Column std',  np.std( np_array, axis=0 ) ) 
print('Row std', np.std( np_array, axis=1 ) ) 

Column std 28.861739379323623


AxisError: axis 1 is out of bounds for array of dimension 1

In [54]:
print('Column sum',  np.sum( np_array, axis=0 ) ) 
print('Row sum', np.sum( np_array, axis=1 ) ) 

Column sum 2450


AxisError: axis 1 is out of bounds for array of dimension 1

In [58]:
print (np_array.shape)
print (np_array.T )
print ( np_array.T.shape)

(50,)
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


# Numpy comparison

In [ ]:
rand_array = np.random.randint(7,50, 100)
print( rand_array )

In [ ]:
rand_array[ rand_array > 18 ]

In [ ]:
rand_array[ rand_array > 30 ]

In [ ]:
rand_array > 30 # this is called a mask

In [ ]:
rand_array[ rand_array % 3 ==0 ]

In [ ]:
print [rand_array[ [0,0,0] ] ]
print [rand_array[ [0,21,-1,-2] ] ]

# Pandas

In [2]:
import pandas as pd

df = pd.DataFrame(
    [ ['Jan',58,42,74,22,2.05],
    ['Feb',61,45,78,26,3.02],
    ['Mar',65,48,84,25,2.34],
    ['Apr',67,50,92,28,1.02],
    ['May',71,53,98,35,0.48],
    ['Jun',75,56,107,41,0.11],
    ['Jul',77,58,105,44,0.0],
    ['Aug',77,59,102,43,0.03],
    ['Sep',77,57,103,40,0.17],
    ['Oct',73,54,96,34,0.81],
    ['Nov',64,48,84,30,1.7],
    ['Dec',58,None,None,21,2.56],
    ['Dec',58,42,73,21,2.56] ],
    columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

In [4]:
df

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [5]:
df.info() # object mean string in Pandas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   month              13 non-null     object 
 1   avg_high           13 non-null     int64  
 2   avg_low            12 non-null     float64
 3   record_high        12 non-null     float64
 4   record_low         13 non-null     int64  
 5   avg_precipitation  13 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 752.0+ bytes


In [6]:
df.describe()

avg_high    avg_low  record_high  record_low  avg_precipitation
count  13.000000  12.000000    12.000000   13.000000          13.000000
mean   67.769231  51.000000    91.333333   31.538462           1.296154
std     7.639305   6.060303    12.323911    8.501131           1.115210
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    61.000000  47.250000    82.500000   25.000000           0.170000
50%    67.000000  51.500000    94.000000   30.000000           1.020000
75%    75.000000  56.250000   102.250000   40.000000           2.340000
max    77.000000  59.000000   107.000000   44.000000           3.020000

In [7]:
df.head()

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34
3   Apr        67     50.0         92.0          28               1.02
4   May        71     53.0         98.0          35               0.48

In [8]:
df.head(3)

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34

In [9]:
df.tail()

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [10]:
list( df.columns )

['month',
 'avg_high',
 'avg_low',
 'record_high',
 'record_low',
 'avg_precipitation']

In [11]:
df.sort_values( 'avg_high' )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56
1    Feb        61     45.0         78.0          26               3.02
10   Nov        64     48.0         84.0          30               1.70
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
9    Oct        73     54.0         96.0          34               0.81
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17

In [12]:
df.sort_values( 'avg_high' , ascending=False )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [15]:
df.sort_values( ['avg_high', 'avg_low'], ascending=False )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
7    Aug        77     59.0        102.0          43               0.03
6    Jul        77     58.0        105.0          44               0.00
8    Sep        77     57.0        103.0          40               0.17
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [16]:
df.sort_values( ['avg_high', 'avg_low'], ascending=[False, True] )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [20]:
df_2 = df.sort_values( ['avg_high', 'avg_low'], ascending=[False, True] )
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [27]:
print (df_2[ 'record_low'] )
print (type(df_2[ 'record_low']) )

8     40
6     44
7     43
5     41
9     34
4     35
3     28
2     25
10    30
1     26
0     22
12    21
11    21
Name: record_low, dtype: int64
<class 'pandas.core.series.Series'>


In [33]:
print (df_2[ ['record_low', 'record_high'] ] )
print (type( df_2[ ['record_low', 'record_high'] ] ) )

    record_low  record_high
8           40        103.0
6           44        105.0
7           43        102.0
5           41        107.0
9           34         96.0
4           35         98.0
3           28         92.0
2           25         84.0
10          30         84.0
1           26         78.0
0           22         74.0
12          21         73.0
11          21          NaN
<class 'pandas.core.frame.DataFrame'>


In [30]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [34]:
df_2[ 'naujas_stulpelis' ] = 5
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    naujas stulpelis  naujas_stulpelis  
8                  5                 5  
6                  5                 5  
7                  5                 5  
5                  5                 5  
9                  5                 5  
4                  5                 5  
3                  5                 5  
2                  5                 5  
10                 5                 5  
1                  5                 5  
0                  5                 5  
12                 5                 5  
11                 5                 5

In [36]:
df_2[ 'naujas_stulpelis_2' ] = (df_2[ 'record_high'] - df_2[ 'record_low' ] ) / 2
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    naujas stulpelis  naujas_stulpelis  naujas_stulpelis_2  
8                  5                 5                31.5  
6                  5                 5                30.5  
7                  5                 5                29.5  
5                  5                 5                33.0  
9                  5                 5                31.0  
4                  5                 5                31.5  
3                  5                 5                32.0  
2                  5                 5                29.5  
10                 5                 5                27.0  
1                  5                 5                26.0  
0                  5                 5                26.0  
12                 5                 5                26.0  
11                 5                 5                 NaN

# loc[index]

In [37]:
df_2.loc[ 10 ]

month                  Nov
avg_high                64
avg_low               48.0
record_high           84.0
record_low              30
avg_precipitation      1.7
naujas stulpelis         5
naujas_stulpelis         5
naujas_stulpelis_2    27.0
Name: 10, dtype: object

In [38]:
df_2.loc[ 8 ]

month                   Sep
avg_high                 77
avg_low                57.0
record_high           103.0
record_low               40
avg_precipitation      0.17
naujas stulpelis          5
naujas_stulpelis          5
naujas_stulpelis_2     31.5
Name: 8, dtype: object

# iloc[ row number ]

In [40]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    naujas stulpelis  naujas_stulpelis  naujas_stulpelis_2  
8                  5                 5                31.5  
6                  5                 5                30.5  
7                  5                 5                29.5  
5                  5                 5                33.0  
9                  5                 5                31.0  
4                  5                 5                31.5  
3                  5                 5                32.0  
2                  5                 5                29.5  
10                 5                 5                27.0  
1                  5                 5                26.0  
0                  5                 5                26.0  
12                 5                 5                26.0  
11                 5                 5                 NaN

In [39]:
df_2.iloc[ 10 ]

month                  Jan
avg_high                58
avg_low               42.0
record_high           74.0
record_low              22
avg_precipitation     2.05
naujas stulpelis         5
naujas_stulpelis         5
naujas_stulpelis_2    26.0
Name: 0, dtype: object

In [41]:
df_2.iloc[ 0 ]

month                   Sep
avg_high                 77
avg_low                57.0
record_high           103.0
record_low               40
avg_precipitation      0.17
naujas stulpelis          5
naujas_stulpelis          5
naujas_stulpelis_2     31.5
Name: 8, dtype: object

In [43]:
df_2.loc[ 5:10 ]

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   

    naujas stulpelis  naujas_stulpelis  naujas_stulpelis_2  
5                  5                 5                33.0  
9                  5                 5                31.0  
4                  5                 5                31.5  
3                  5                 5                32.0  
2                  5                 5                29.5  
10                 5                 5                27.0

In [46]:
df_2.loc[ [ 5,6,7,8,9,10 ] ]

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
5    Jun        75     56.0        107.0          41               0.11   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
8    Sep        77     57.0        103.0          40               0.17   
9    Oct        73     54.0         96.0          34               0.81   
10   Nov        64     48.0         84.0          30               1.70   

    naujas stulpelis  naujas_stulpelis  naujas_stulpelis_2  
5                  5                 5                33.0  
6                  5                 5                30.5  
7                  5                 5                29.5  
8                  5                 5                31.5  
9                  5                 5                31.0  
10                 5                 5                27.0

In [47]:
df_2.loc[ [ 5,6,7,8,9,10 ] , 'avg_high' ]

5     75
6     77
7     77
8     77
9     73
10    64
Name: avg_high, dtype: int64

In [48]:
df_2.loc[ [ 5,6,7,8,9,10 ] , [ 'avg_high', 'record_high' ] ]

avg_high  record_high
5         75        107.0
6         77        105.0
7         77        102.0
8         77        103.0
9         73         96.0
10        64         84.0

In [49]:
df_2.loc[ : , ['avg_high', 'record_high' ] ]

avg_high  record_high
8         77        103.0
6         77        105.0
7         77        102.0
5         75        107.0
9         73         96.0
4         71         98.0
3         67         92.0
2         65         84.0
10        64         84.0
1         61         78.0
0         58         74.0
12        58         73.0
11        58          NaN

# changing row indexes

In [50]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    naujas stulpelis  naujas_stulpelis  naujas_stulpelis_2  
8                  5                 5                31.5  
6                  5                 5                30.5  
7                  5                 5                29.5  
5                  5                 5                33.0  
9                  5                 5                31.0  
4                  5                 5                31.5  
3                  5                 5                32.0  
2                  5                 5                29.5  
10                 5                 5                27.0  
1                  5                 5                26.0  
0                  5                 5                26.0  
12                 5                 5                26.0  
11                 5                 5                 NaN

In [51]:
df_3 = df_2.set_index('month')
df_3

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Jul          77     58.0        105.0          44               0.00   
Aug          77     59.0        102.0          43               0.03   
Jun          75     56.0        107.0          41               0.11   
Oct          73     54.0         96.0          34               0.81   
May          71     53.0         98.0          35               0.48   
Apr          67     50.0         92.0          28               1.02   
Mar          65     48.0         84.0          25               2.34   
Nov          64     48.0         84.0          30               1.70   
Feb          61     45.0         78.0          26               3.02   
Jan          58     42.0         74.0          22               2.05   
Dec          58     42.0         73.0          21               2.56   
Dec          58      NaN          NaN          21               2.56   

       naujas stulpelis  naujas_stulpelis  naujas_stulpelis_2  
month                                                          
Sep                   5                 5                31.5  
Jul                   5                 5                30.5  
Aug                   5                 5                29.5  
Jun                   5                 5                33.0  
Oct                   5                 5                31.0  
May                   5                 5                31.5  
Apr                   5                 5                32.0  
Mar                   5                 5                29.5  
Nov                   5                 5                27.0  
Feb                   5                 5                26.0  
Jan                   5                 5                26.0  
Dec                   5                 5                26.0  
Dec                   5                 5                 NaN

In [52]:
df_3.loc[ 'Sep' ]

avg_high               77.00
avg_low                57.00
record_high           103.00
record_low             40.00
avg_precipitation       0.17
naujas stulpelis        5.00
naujas_stulpelis        5.00
naujas_stulpelis_2     31.50
Name: Sep, dtype: float64

In [53]:
df_3.loc[ [ 'Sep', 'Dec' ] ]

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Dec          58     42.0         73.0          21               2.56   
Dec          58      NaN          NaN          21               2.56   

       naujas stulpelis  naujas_stulpelis  naujas_stulpelis_2  
month                                                          
Sep                   5                 5                31.5  
Dec                   5                 5                26.0  
Dec                   5                 5                 NaN

In [54]:
# df_3.iloc[ 'Sep' ] - neveiks
df_3.iloc[ 0 ]

avg_high               77.00
avg_low                57.00
record_high           103.00
record_low             40.00
avg_precipitation       0.17
naujas stulpelis        5.00
naujas_stulpelis        5.00
naujas_stulpelis_2     31.50
Name: Sep, dtype: float64

In [56]:
df_3.dropna()
df_3

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Jul          77     58.0        105.0          44               0.00   
Aug          77     59.0        102.0          43               0.03   
Jun          75     56.0        107.0          41               0.11   
Oct          73     54.0         96.0          34               0.81   
May          71     53.0         98.0          35               0.48   
Apr          67     50.0         92.0          28               1.02   
Mar          65     48.0         84.0          25               2.34   
Nov          64     48.0         84.0          30               1.70   
Feb          61     45.0         78.0          26               3.02   
Jan          58     42.0         74.0          22               2.05   
Dec          58     42.0         73.0          21               2.56   
Dec          58      NaN          NaN          21               2.56   

       naujas stulpelis  naujas_stulpelis  naujas_stulpelis_2  
month                                                          
Sep                   5                 5                31.5  
Jul                   5                 5                30.5  
Aug                   5                 5                29.5  
Jun                   5                 5                33.0  
Oct                   5                 5                31.0  
May                   5                 5                31.5  
Apr                   5                 5                32.0  
Mar                   5                 5                29.5  
Nov                   5                 5                27.0  
Feb                   5                 5                26.0  
Jan                   5                 5                26.0  
Dec                   5                 5                26.0  
Dec                   5                 5                 NaN

In [57]:
df_3.to_csv("weather.csv")