# Numpy

## 2D array

In [4]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [2]:
import numpy as np

In [9]:
np_array = np.array( a_list )
print(np_array)
print(type(np_array) )
print(np_array[1])
print(np_array[1][1])
print(np_array[1, 1], '\n') # [row index, column index]

print( np_array[ :, 0 ] )
print( np_array[ :, 2 ], '\n' )

print( np_array[ :2, 0 ], '\n' )

print( np_array[ :2, 1:3 ], '\n' )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
[5 6 7 8]
6
6 

[1 5 9]
[ 3  7 11] 

[1 5] 

[[2 3]
 [6 7]] 



In [10]:
print ( np_array.shape )
print (len(np_array) )

(3, 4)
3


In [12]:
print (np_array[ :2, 1:3 ].shape )

(2, 2)


# 1D array

In [13]:
array_1d = np.array( [1,5,7,9,71,14] )

print

In [15]:
list_1d = [1,5,7,9,71,14]
print ( list_1d * 3 )
print ( [ number * 3 for number in list_1d ] )
print ('numpy array')
print ( array_1d * 3 )
print ( array_1d / 3 )
print ( array_1d + 3 )
print ( array_1d % 2 )
print ( array_1d ** 5 )

[1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14]
[3, 15, 21, 27, 213, 42]
numpy array
[  3  15  21  27 213  42]
[ 0.33333333  1.66666667  2.33333333  3.         23.66666667  4.66666667]
[ 4  8 10 12 74 17]
[1 1 1 1 1 0]
[         1       3125      16807      59049 1804229351     537824]


In [17]:
print (array_1d)
list_1d = [1,5,7,9,71,14]
print (list_1d)
list_1d[2:4] = [10,25]
print (list_1d)
# list_1d[2:4] = 50 # error
# print (list_1d)
print ('numpy array')
array_1d[2:4] = [10,25]
print (array_1d)
array_1d[2:4] = 55
print (array_1d)

[ 1  5  7  9 71 14]
[1, 5, 7, 9, 71, 14]
[1, 5, 10, 25, 71, 14]
numpy array
[ 1  5 10 25 71 14]
[ 1  5 55 55 71 14]


# 3D array

In [20]:
arr_3d = np.array([
        [ 
            [1, 2, 3], 
            [4, 5, 6]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)
print (arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [19]:
print ( arr_3d.shape )

(2, 2, 3)


In [21]:
arr_3d[:, :, 2] = 10
print(arr_3d)
arr_3d[:, :, 2] = 55
print(arr_3d)

[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [ 4  5 10]]]
[[[ 1  2 55]
  [ 4  5 55]]

 [[ 1  2 55]
  [ 4  5 55]]]


In [23]:
arr_3d[:, :, 2] = 10
print(arr_3d)
arr_3d[1, 1, :2] = 55
print(arr_3d)

[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [ 4  5 10]]]
[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [55 55 10]]]


# Numpy speed

In [24]:
size = 1_000_000

In [25]:
%%timeit # Jupyter komanda

py_list = list(range(size))

440 ms ± 139 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
%%timeit

np_arr = np.arange(size)

38.4 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
%%timeit

py_list_2 = [ number * 2 for number in py_list ]

NameError: name 'py_list' is not defined

In [29]:
%%timeit

np_rez = np_arr * 2

NameError: name 'np_arr' is not defined

# Numpy reshape

In [ ]:
np_array = np.arange(0,100,2)
print(np_array)
print(np_array.shape)
print( np_array.reshape( (5,10) ), '\n' )

# Numpy methods

In [30]:
array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [2,2], [4,3], [7,4] ],
    [ [3,2], [4,3], [7,4] ],
    [ [4,2], [4,3], [7,4] ],
]
)

print (array_3d.shape)

(4, 3, 2)


In [31]:
print (array_3d)

[[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]


In [32]:
np.mean (array_3d)

3.75

In [33]:
np.mean (array_3d, axis=0 )

array([[2.5, 2. ],
       [4. , 3. ],
       [7. , 4. ]])

In [34]:
np.mean (array_3d, axis=1 )

array([[4.        , 3.        ],
       [4.33333333, 3.        ],
       [4.66666667, 3.        ],
       [5.        , 3.        ]])

In [35]:
np.mean (array_3d, axis=2 )

array([[1.5, 3.5, 5.5],
       [2. , 3.5, 5.5],
       [2.5, 3.5, 5.5],
       [3. , 3.5, 5.5]])

In [ ]:
np.array = np.arange(0,20),reshape( (5,4) )
print (np_array)

In [ ]:
print('Column mean',  np.mean( np_array, axis=0 ) )
print('Row mean', np.mean( np_array, axis=1 ) )

# Numpy comparison

In [ ]:
rand_array = np.random.randint(7,50, 100)
print( rand_array )

# Pandas

In [ ]:
import pandas as pd

df = pd.DataFrame(
    [ ['Jan',58,42,74,22,2.05],
    ['Feb',61,45,78,26,3.02],
    ['Mar',65,48,84,25,2.34],
    ['Apr',67,50,92,28,1.02],
    ['May',71,53,98,35,0.48],
    ['Jun',75,56,107,41,0.11],
    ['Jul',77,58,105,44,0.0],
    ['Aug',77,59,102,43,0.03],
    ['Sep',77,57,103,40,0.17],
    ['Oct',73,54,96,34,0.81],
    ['Nov',64,48,84,30,1.7],
    ['Dec',58,None,None,21,2.56],
    ['Dec',58,42,73,21,2.56] ],
    columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

: 

In [ ]:
print (df)

In [ ]:
df.describe()

In [ ]:
df.head()

In [ ]:
df.head(3)

In [ ]:
df.tail()

In [ ]:
list( df.columns )

In [ ]:
df.sort_values( 'avg_high' )

In [ ]:
df.sort_values( 'avg_high' , ascending=False )

In [ ]:
df_2 = df.sort_values( ['avg_high, avg_low'], ascending )

In [ ]:
print (df_2[ 'record'])